version: '2'

services:
  auto-tests:
    container_name: "aqa-playwright"
    build:
      context: .
      args:
        HTTP_CREDENTIAL_USERNAME: ${HTTP_CREDENTIAL_USERNAME}
        HTTP_CREDENTIAL_PASSWORD: ${HTTP_CREDENTIAL_PASSWORD}
