FROM mcr.microsoft.com/playwright:v1.39.0-jammy

ARG HTTP_CREDENTIAL_USERNAME
ARG HTTP_CREDENTIAL_PASSWORD

ENV HTTP_CREDENTIAL_USERNAME=HTTP_CREDENTIAL_USERNAME
ENV HTTP_CREDENTIAL_PASSWORD=HTTP_CREDENTIAL_PASSWORD

COPY . /aqa-playwright
WORKDIR /aqa-playwright

RUN npm ci

CMD ["npm", "test"]
